### ISSUE TITLE
Make example invoice public

### ISSUE THREAD

**Issue by izomeraza** [wemake-services/meta#66]
An [example invoice google sheet](https://docs.google.com/spreadsheets/d/1hVaCX4ALWDAYYxOlJ5m8hjwdXEBFcessYn6NUHQOujo/edit?usp=sharing) on the [billing page](https://wemake.services/meta/rsdp/billing/) currently requires permission to be viewed.

"Want in? Ask for access, or switch to an account with permission." 

Looks reasonable to make it publicly accessible.

**Comment by sobolevn** [comment]
I have changed access level to `Anyone with the link`.

![2018-05-14 16 56 50](https://user-images.githubusercontent.com/4660275/40001874-d2392ec4-5797-11e8-8ec9-778f1165a642.png)
