### ISSUE TITLE
Test assignment

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/meta#7]
## Github repository browsing tool

This task looks like a average task you will receive from us. But it's scope is bigger than usual, since we want to see as much skills as possible.

### Subject

We need to create a third-party service to list user's Github repositories.

So, the process is:
1. You log in to Github
2. You log in to our service with Github account
3. It shows a list of all your repositories, your avatar, and username on the same page

### Extra

We also want to know the author of this service. Please, provide a link to the source code on the bottom of the page in a form of: `Created by <link-to-your-account>, source code: <link-to-the-github-repo>.`

### Technologies

Fill free to use any tools you like (minding the license). But, note that you are limited to the platform. 
If you are applying to `python` position it would be very strange to submit a `js` solution.

### Result

This should be 100% working and deployed service. You should provide a live link for us to browse it.

### Time

Time estimated: from 2 to 3 hours
If it takes more than that, well, I guess you are doing something wrong.

### Process

That's how we work internally, maybe it would be helpful: http://wemake.services/meta/employees

**Comment by chadwhitacre** [comment]
> Make sure you don’t have any questions. If you do, please, freely [ask them](https://github.com/wemake-services/meta/issues/7) in a GitHub issue.

Okay ...

The pronouns in the "Subject" section are unclear. Here's my interpretation:

1. A user logs in to GitHub.
1. The user logs in to the service with their GitHub account.
1. The service shows a list of all of the user's repositories, the user's avatar, and username on the same page.

Is my interpretation correct? :)

**Comment by sobolevn** [comment]
@chadwhitacre yes, it is 🙂

**Comment by serhii73** [comment]
Does the service show a list of public and private of the user's repositories or only public?

**Comment by sobolevn** [comment]
Only public.

**Comment by Islamnader94** [comment]
Do I need to create a UI for the end results?

**Comment by sobolevn** [comment]
Just a simple one.

**Comment by amihaiemil** [comment]
@sobolevn Any chance for a Java project in your team? Or still just Python? :)

**Comment by sobolevn** [comment]
@amihaiemil yes, we still only do [`python`](https://github.com/wemake-services/wemake-django-template), [`typescript`](https://github.com/wemake-services/wemake-vue-template), `elixir` (very little) projects. I am pretty sure that we will add `rust` at some point. But, not yet 😞

**Comment by Mohammad-Jouza** [comment]
@sobolevn Do you need a MERN stack developer (MongoDB, Express, React, Node js) [Javascript]

**Comment by sobolevn** [comment]
@Mohammad-Jouza not in the moment, sorry. We also tend to use [`Vue`](https://github.com/wemake-services/wemake-vue-template) more than React (if it is important for you).
 
But, we have quite a big problem with frontend developers. So, we try to keep a number of available contractors as high as possible. Because, when we need them - it is hard to find one!

**Comment by DOBRO-228** [comment]
"Fill free to use any tools you like..." - "feel" ?

**Comment by MohammadJouza** [comment]
@sobolevn 
in these two years, I established an academy that teaches full-stack development 
So if you like we can recommend our graduate to you
and you interview them and hire who you think is fit (after giving them a task to evaluate their skills)

We provide a high-quality learning experience for our students as we have our industry-driven curriculum, various teaching methodologies, and a system that competes with world-class Coding Bootcamps. I have no doubt this will end up being a significant success if we make it happen.

Feel free to contact me any time
m.jouza@meraki-academy.org
http://www.meraki-academy.org/

**Comment by cingh-jasdeep** [comment]
Are you looking for a Vuejs Developer right now?
I had submitted a job application but never got any reply!

**Comment by cingh-jasdeep** [comment]
Do you have a vacancy for a Vuejs Developer?
I had submitted a job application but never got a reply!

**Comment by uhbif19** [comment]
Your email and job application form are not working.

**Comment by uhbif19** [comment]
@sobolevn Are wemake.services still alive?

**Comment by sobolevn** [comment]
We do consulting now, web development is long gone :)

**Comment by uhbif19** [comment]
@sobolevn So this task should be closed?

**Comment by a-wakeel** [comment]
The task is closed, how can we apply now? The website is guiding to this task.

**Comment by ghorus** [comment]
Hi, are you guys still accepting applications?

**Comment by sobolevn** [comment]
No, sorry :(
