### ISSUE TITLE
Typo on "Roles and responsibilities for the project" page

### ISSUE THREAD

**Issue by narimanized** [wemake-services/meta#99]
I believe that good project deserves better.
https://github.com/wemake-services/meta/blob/0dcc3301e727fe7384681ec5d840f0609a2fac95/_rsdp/roles-and-responsibilities.md#L29 Missed "manager".

**Comment by sobolevn** [comment]
@narimanized thanks! Willing to send a PR with the fix?

**Comment by narimanized** [comment]
I will. In a minute.
